baseURL: "https://tehlug.org/"
languageCode: "fa-ir"
title: "تهران‌لاگ"
theme: "Tehlug-Hugo-Theme"
paginate: 3
favicon: static/favicon.ico

params:
  subtitle: "گروه کاربران گنو/لینوکس تهران"
  mapView: 0.002
  mode: "auto"

  excludedTypes: [gallery]
  mainSections: [event, news]

  menu:
    items:
      [
        { title: "تهران‌لاگ", url: "/about-tehlug", name: "", name: "about-tehlug" },
        { title: "جلسات", url: "/events", name: "events" },
        # { title: "جلسات آینده", url: "/calendar", name: "calendar" }, ## برای ۴ سال پیشه این صفحه. بودنش باعث سردرگمی و اشتباه میشه
        { title: "اخبار", url: "/news", name: "news" },
        { title: "موضوعات", url: "/topics", name: "topics" },
        { title: "ارائه دهندگان", url: "/speakers", name: "speakers" },
        { title: "تصاویر", url: "/images", name: "images" },
        { title: "انجمن (جدید)", url: "https://forum.tehlug.org", name: "forum" },
      ]

  footer:
    items:
      [
        { title: "پرسش‌های پرتکرار", url: "/faq" },
        { title: "بایگانی", url: "https://archive.org/details/@tehlug" },
        { title: "گیت‌هاب", url: "https://github.com/tehlug" },
        { title: "ترلو", url: "https://trello.com/tehlug" },
        { title: "تلگرام", url: "https://t.me/TehranLug" },
        { title: "گروه تلگرام", url: "https://t.me/TehlugGp" },
        { title: "ماستودون", url: "https://mastodon.social/@tehlug", rel: "me"},
        { title: "توییتر", url: "https://twitter.com/tehlug" },
        { title: "یوتیوب", url: "https://youtube.com/@TehranLUG" },
        { title: "اینستاگرم", url: "https://instagram.com/tehlug" },
        { title: "ایوند", url: "https://evand.com/organizations/tehlug" },
        { title: "لینکداین", url: "https://linkedin.com/company/tehlug/" },
        { title: "گوگل کلندر", url: "https://calendar.google.com/calendar?cid=MHY3M3Z0czVoYnU5N3Nmajk0Mzdtcmc1cGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ" },
      ]

taxonomies:
  topics: "topics"
  speakers: "speakers"
  locations: "locations"
  participants: "participants"
